/* Wallet, profile and referral center. This intentionally stays in demo mode. */
(() => {
  const body=document.body;
  const money='KSh';
  const modal=document.createElement('div'); modal.className='account-modal'; modal.innerHTML=`<div class="account-dialog" role="dialog" aria-modal="true"><button class="account-close" aria-label="Close">×</button><span class="eyebrow">ACCOUNT CENTER</span><h2 id="accountTitle">Wallet</h2><div id="accountContent"></div></div>`;body.append(modal);
  const content=modal.querySelector('#accountContent');
  const profile=JSON.parse(localStorage.getItem('win254-profile')||'null')||{balance:10000,bonus:0,referrals:0,code:'WIN254-'+Math.random().toString(36).slice(2,8).toUpperCase()};
  localStorage.setItem('win254-profile',JSON.stringify(profile));
  const save=()=>localStorage.setItem('win254-profile',JSON.stringify(profile));
  function open(title,html){modal.querySelector('#accountTitle').textContent=title;content.innerHTML=html;modal.classList.add('open');}
  function demoNotice(action){open(action,`<div class="demo-alert"><strong>Demo only</strong><p>This ${action.toLowerCase()} button is a visual demonstration. No payment provider, deposit, withdrawal, wallet transfer or real-money transaction is connected.</p></div><button class="primary-button full" data-close>Return to Win254</button>`);content.querySelector('[data-close]').onclick=close;}
  function close(){modal.classList.remove('open')}
  function wallet(){open('Wallet',`<div class="wallet-balance"><span>Demo balance</span><strong>${money} ${profile.balance.toLocaleString()}</strong></div><div class="wallet-actions"><button class="primary-button" data-deposit>Deposit</button><button class="outline-button" data-withdraw>Withdraw</button></div><p class="account-muted">Demo credits only. Real payments are disabled.</p>`);content.querySelector('[data-deposit]').onclick=()=>demoNotice('Deposit');content.querySelector('[data-withdraw]').onclick=()=>demoNotice('Withdrawal');}
  function profileView(){const user=window.win254User;open('My profile',`<div class="profile-row"><div class="avatar">${(user?.name||'Guest').slice(0,1).toUpperCase()}</div><div><strong>${user?.name||'Guest player'}</strong><small>${user?.email||'Log in to unlock your profile'}</small></div></div><div class="account-stats"><div><b>${money} ${profile.balance.toLocaleString()}</b><small>Demo balance</small></div><div><b>${profile.referrals}</b><small>Referrals</small></div><div><b>0</b><small>Open bets</small></div></div><button class="primary-button full" data-wallet>Open wallet</button>`);content.querySelector('[data-wallet]').onclick=wallet;}
  function referrals(){open('Refer & earn',`<div class="referral-card"><span>Your referral code</span><strong>${profile.code}</strong><button class="outline-button" data-copy>Copy code</button></div><p>Invite friends to explore Win254. Any future reward programme must be subject to eligibility, anti-fraud checks and local gambling law.</p><button class="primary-button full" data-share>Share invite</button>`);content.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(profile.code);showToast('Referral code copied')}catch{showToast(profile.code)}};content.querySelector('[data-share]').onclick=()=>{if(navigator.share)navigator.share({title:'Win254',text:`Join me on Win254 with code ${profile.code}`}).catch(()=>{});else showToast(`Share code: ${profile.code}`)};}
  document.addEventListener('click',e=>{if(e.target.closest('[data-account]'))profileView();if(e.target.closest('[data-wallet]'))wallet();if(e.target.closest('[data-referrals]'))referrals()});
  modal.querySelector('.account-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  function showToast(m){window.showToast?.(m)}
  const actions=document.createElement('div');actions.className='account-actions';actions.innerHTML='<button class="outline-button" data-wallet>Wallet</button><button class="outline-button" data-account>Profile</button><button class="primary-button" data-referrals>Refer & earn</button>';document.querySelector('.top-actions').prepend(actions);
  window.win254DemoWallet=profile;save();
})();
