/* Worldwide sports catalogue and provider-ready event browser. */
(() => {
  const catalog = [
    ['Football','International','World Cup Qualifiers','🇺🇳'],['Football','England','Premier League','🏴'],['Football','Spain','La Liga','🇪🇸'],['Football','Germany','Bundesliga','🇩🇪'],['Football','Italy','Serie A','🇮🇹'],['Football','France','Ligue 1','🇫🇷'],['Football','Kenya','FKF Premier League','🇰🇪'],
    ['Basketball','USA','NBA','🇺🇸'],['Basketball','Europe','EuroLeague','🇪🇺'],['Basketball','Kenya','KBF Premier League','🇰🇪'],['Tennis','World','ATP Tour','🎾'],['Tennis','World','WTA Tour','🎾'],['Cricket','International','ICC T20','🏏'],['Cricket','England','The Hundred','🏏'],['Rugby','International','Rugby Championship','🏉'],['Rugby','Europe','Six Nations','🏉'],['Baseball','USA','MLB','⚾'],['Ice Hockey','USA','NHL','🏒'],['Ice Hockey','Europe','Champions Hockey League','🏒'],['Volleyball','International','Nations League','🏐'],['Handball','Europe','EHF Champions League','🤾'],['Motorsport','World','Formula 1','🏎️'],['Golf','World','PGA Tour','⛳'],['Boxing','World','Boxing','🥊'],['MMA','World','UFC','🥋'],['Esports','World','Global Esports','🎮']
  ];
  const teams = {Football:['Manchester City','Liverpool'],Basketball:['Lakers','Celtics'],Tennis:['S. Williams','I. Swiatek'],Cricket:['Kenya','South Africa'],Rugby:['New Zealand','Australia'],Baseball:['Yankees','Dodgers'],'Ice Hockey':['Rangers','Bruins'],Volleyball:['Brazil','Italy'],Handball:['Barcelona','Kiel'],Motorsport:['Red Bull Racing','McLaren'],Golf:['R. McIlroy','S. Scheffler'],Boxing:['Champion A','Champion B'],MMA:['Fighter A','Fighter B'],Esports:['Team Liquid','G2 Esports']};
  const makeEvents = () => catalog.map((row,i) => { const pair=teams[row[0]]||['Home','Away']; return {id:`world-${i}`,sport:row[0],country:row[1],league:row[2],icon:row[3],home:pair[0],away:pair[1],status:i%5===0?'LIVE':'UPCOMING',score:i%5===0?`${i%3} — ${i%2}`:'—',odds:[['1',(1.35+(i%9)*.11).toFixed(2)],['X',(2.7+(i%7)*.31).toFixed(2)],['2',(1.55+(i%8)*.17).toFixed(2)]]}; });
  let events=[]; let sport='all'; let country='all'; let league='all';
  const $=s=>document.querySelector(s);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function controls(){const heading=$('.events-column .section-heading');if(!heading||$('#worldFilters'))return;const box=document.createElement('div');box.id='worldFilters';box.className='world-filters';box.innerHTML='<input id="eventSearch" placeholder="Search worldwide events" aria-label="Search worldwide events"><select id="sportSelect"><option value="all">All sports</option></select><select id="countrySelect"><option value="all">All countries</option></select><select id="leagueSelect"><option value="all">All leagues</option></select>';heading.after(box);['sportSelect','countrySelect','leagueSelect'].forEach(id=>$('#'+id).onchange=()=>{if(id==='sportSelect')sport=$('#'+id).value;if(id==='countrySelect')country=$('#'+id).value;if(id==='leagueSelect')league=$('#'+id).value;render()});$('#eventSearch').oninput=render;}
  function fillFilters(){const add=(id,values)=>{const el=$('#'+id);if(!el)return;el.innerHTML='<option value="all">All '+(id==='sportSelect'?'sports':id==='countrySelect'?'countries':'leagues')+'</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')};add('sportSelect',[...new Set(events.map(e=>e.sport))]);add('countrySelect',[...new Set(events.map(e=>e.country))]);add('leagueSelect',[...new Set(events.map(e=>e.league))]);}
  function render(){const q=($('#eventSearch')?.value||'').toLowerCase();const list=$('#eventList');const visible=events.filter(e=>(sport==='all'||e.sport===sport)&&(country==='all'||e.country===country)&&(league==='all'||e.league===league)&&(`${e.home} ${e.away} ${e.league} ${e.country}`.toLowerCase().includes(q)));list.innerHTML=visible.map(e=>`<article class="event-card worldwide-card"><div class="event-meta"><span>${esc(e.icon)} ${esc(e.country)} · ${esc(e.league)}</span><span class="${e.status==='LIVE'?'live':''}">${e.status==='LIVE'?'● ':''}${e.status}</span></div><div class="teams"><div class="team"><span class="team-logo">${esc(e.icon)}</span>${esc(e.home)}</div><div class="score">${e.score}</div><div class="team"><span>${esc(e.away)}</span><span class="team-logo">${esc(e.icon)}</span></div></div><div class="markets">${e.odds.map((o,i)=>`<button class="odd" data-world-event="${e.id}" data-world-index="${i}">${o[0]} <b>${o[1]}</b></button>`).join('')}</div></article>`).join('')||'<div class="world-empty">No events match those filters. Try another sport or league.</div>';list.querySelectorAll('[data-world-event]').forEach(b=>b.onclick=()=>{const e=events.find(x=>x.id===b.dataset.worldEvent);window.showToast?.(`${e.home} v ${e.away} added to demo selection`)})}
  async function init(){controls();events=makeEvents();fillFilters();render();const note=document.createElement('p');note.className='provider-note';note.textContent='Worldwide catalogue demo · connect a licensed sports-data provider through /api/sports/events for live fixtures and odds.';$('#worldFilters')?.after(note);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
